config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'
  get '/about', to: 'public/homes#about', as: 'about'
  get 'orders/thanks', to: 'public/orders#thanks', as: 'thanks'
  

  scope module: :public do
    get '/customers', to: 'customers#show', as: 'my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'my_page_edit'
    patch '/customers', to: 'customers#update', as: 'my_page_update'
    get '/customers/confirm', to: 'customers#confirm', as: 'confirm'
    patch '/customers/cancel', to: 'customers#cancel', as: 'cancel'
    post '/orders/confirm', to: 'orders#confirm', as: 'order_confirm'
    
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :new, :create, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    
  end
  namespace :admin do
    get '/', to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  validates :payment_method, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :total_amount, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def subtotal
    item.taxin_price * amount
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(@order.customer_id)
    @order_details = OrderDetail.where(order_id: @order.id)
    @total_price = 0
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      @order_details.update_all(making_status: "production_pending") if @order.status == "payment_confirmation"
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
  def order_detail_params
    params.require(:order).permit(:making_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-4">
    <h3>注文履歴詳細</h3>
  </div>
  <div class="row">
    <p class="col-2"><strong>購入者</strong></p>
    <%= form_tag admin_path, method: :get, class: 'boards__searchForm' do %>
      <p class="col-auto">
        <%= link_to @order.customer.last_name + @order.customer.first_name, admin_path(customer_id: @customer.id) %>
      </p>
    <% end %>
  </div>
  <div class="row">
    <p class="col-2"><strong>注文日</strong></p>
    <p class="col-10"><%= @order.created_at.strftime('%Y/%m/%d') %></p>
  </div>
  <div class="row">
    <p class="col-2"><strong>配送先</strong></p>
    <p class="col-10"><%= "〒" + @order.postal_code %> <%= @order.address %><br><%= @order.name %></p>
  </div>
  <div class="row">
    <p class="col-2"><strong>支払方法</strong></p>
    <p class="col-10"><%= @order.payment_method_i18n %></p>
  </div>
  <div class="row">
    <p class="col-2"><strong>注文ステータス</strong></p>
    <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
      <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>　<%= f.submit '更新', class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-8">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品名</th><th>単価（税込）</th><th>数量</th><th>小計</th><th>製造ステータス</th><th></th>
          </tr>
        </thead>
        <tbody>
          
            <% @order_details.each do |order_detail| %>
              <tr>
                <td><%= order_detail.item.name %></td><td><%= order_detail.price %></td><td><%= order_detail.amount %></td><td><%= order_detail.price * order_detail.amount %></td>
                <td>
                  <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
                    <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k] } %></td><td><%= f.submit '更新', class: "btn btn-success" %>
                    <% end %>
                  </td>
                <% @total_price += order_detail.price * order_detail.amount %>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4 d-flex align-items-end">
      <table>
        <tr>
          <th>商品合計</th><td><%= @total_price %></td>
        </tr>
        <tr>
          <th>送料</th><td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th>請求金額合計</th><td><%= @order.total_amount %></td>
        </tr>
      </table>
    </div>
  </div>