config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'
  get '/about', to: 'public/homes#about', as: 'about'
  get 'orders/thanks', to: 'public/orders#thanks', as: 'thanks'
  

  scope module: :public do
    get '/customers', to: 'customers#show', as: 'my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'my_page_edit'
    patch '/customers', to: 'customers#update', as: 'my_page_update'
    get '/customers/confirm', to: 'customers#confirm', as: 'confirm'
    patch '/customers/cancel', to: 'customers#cancel', as: 'cancel'
    post '/orders/confirm', to: 'orders#confirm', as: 'order_confirm'
    
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :new, :create, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    
  end
  namespace :admin do
    get '/', to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + '　' +  address + '　' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.taxin_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :item_image, presence: true
  
  def taxin_price
    (price * 1.1).floor
  end
  
  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  validates :payment_method, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :total_amount, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def subtotal
    item.taxin_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    item.taxin_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :index
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = params[:customer_id].present? ? Customer.find(params[:customer_id]).orders.page(params[:page]).per(10) : Order.all.page(params[:page]).per(10)
    @customer = params[:customer_id].present? ? Customer.find(params[:customer_id]).last_name + Customer.find(params[:customer_id]).first_name + "さんの" : ""
    @order_amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @tax_included_price = @item.price * 1.1
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :item_image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(@order.customer_id)
    @order_details = OrderDetail.where(order_id: @order.id)
    @total_price = 0
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      @order_details.update_all(making_status: "production_pending") if @order.status == "payment_confirmation"
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
  def order_detail_params
    params.require(:order).permit(:making_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/_header.html.erb
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <span class="navbar-brand">ながのCAKE</span>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <% if admin_signed_in? %>
                <li class="nav-item">
                        <%= link_to '商品一覧', items_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to '会員一覧', customers_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'ジャンル一覧', genres_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to 'About', about_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to '商品一覧', about_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'ログイン', new_admin_session_path, class: 'nav-link text-light' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row mt-4">
    <h3><%= @customer %>注文履歴一覧</h3>
  </div>
  <div class="row justify-content-center">
    <div class="col-8">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>購入日時</th><th>購入者</th><th>注文個数</th><th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id), class: "text-reset" do %>
                <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
              <% end %>
            </td>
            <td><%= order.customer.last_name + order.customer.first_name %></td>
            <% order.order_details.each do |order_detail| %>
              <% @order_amount += order_detail.amount %>
            <% end %>
            <td><%= @order_amount %></td>
            <% @order_amount = 0 %>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>