config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top", as: 'top'
  get '/about', to: 'public/homes#about', as: 'about'
  get 'orders/thanks', to: 'public/orders#thanks', as: 'thanks'
  

  scope module: :public do
    get '/customers', to: 'customers#show', as: 'my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'my_page_edit'
    patch '/customers', to: 'customers#update', as: 'my_page_update'
    get '/customers/confirm', to: 'customers#confirm', as: 'confirm'
    patch '/customers/cancel', to: 'customers#cancel', as: 'cancel'
    post '/orders/confirm', to: 'orders#confirm', as: 'order_confirm'
    
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :new, :create, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    
  end
  namespace :admin do
    get '/', to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + '　' +  address + '　' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.taxin_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :item_image, presence: true
  
  def taxin_price
    (price * 1.1).floor
  end
  
  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  validates :payment_method, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :total_amount, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def subtotal
    item.taxin_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    item.taxin_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :index
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = params[:customer_id].present? ? Customer.find(params[:customer_id]).orders.page(params[:page]).per(10) : Order.all.page(params[:page]).per(10)
    @customer = params[:customer_id].present? ? Customer.find(params[:customer_id]).last_name + Customer.find(params[:customer_id]).first_name + "さんの" : ""
    @order_amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
    @genres = Genre.all
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @tax_included_price = @item.price * 1.1
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :item_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if admin_signed_in? %>
          <span class="navbar-brand">ながのCAKE</span>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
            </ul>
          </div>
          <% elsif customer_signed_in? %>
            <%= link_to top_path do %>
              <span class="navbar-brand">ながのCAKE</span>
            <% end %>
            <div class="collapse navbar-collapse justify-content-end">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to 'マイページ', my_page_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to '商品一覧', items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'カート', cart_items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              </ul>
            </div>
          <% else %>
            <%= link_to top_path do %>
              <span class="navbar-brand">ながのCAKE</span>
            <% end %>
            <div class="collapse navbar-collapse justify-content-end">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'About', about_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                    <%= link_to '商品一覧', items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                    <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-light' %>
                </li>
              </ul>
            </div>
          <% end %>
        </nav>
    </header>
    <%= yield %>
  </body>
</html>